export { default as User } from './User'
export { default as Service } from './Service'
export { default as AboutUs } from './AboutUs'
export { default as Portfolio } from './Portfolio'
export { default as Appointment } from './Appointment'
export { default as Article } from './Article'
